### ISSUE TITLE
Packages/Compiling

### ISSUE THREAD

**Issue by TimPGamer** [MarcelCoding/dynmap-ftb-chunks#2]
Hi MarcelCoding,
i just wanted to check out this dynmap plugin, so i tried building it.
But i have noticed, that maven.latmod.com has moved to maven.letvain.dev.
Sadly there is no FTBLib or FTBUtilities uploaded there, so its not possible to build the mod.
I am not that experienced on how to build mods, so i wanted to ask, if u can either tell me a 
workaround or just upload a package containing the built mod.
-Tim

**Comment by MarcelCoding** [comment]
This is just a fork, please have a look at the original repository.

**Comment by TimPGamer** [comment]
THIS IS A FORK? i didnt even know????

**Comment by MarcelCoding** [comment]
Take a look in the commit history, none of the commits is authored by me.

**Comment by TimPGamer** [comment]
Bruh. Sry.

**Comment by MarcelCoding** [comment]
All good, no problem :)
